Repository IT-Cotato/11th-Troublog-BE, pull requests merged in 2025-07, with the labels that each got.

#12 [Config] .coderabbit.yaml 파일 수정 및 리뷰 테스트
  .coderabbit.yaml
Labels: 🔧 config

#15 [Feat] CI/CD 파이프라인 구축
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  gradlew
  nginx/nginx.conf
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/troublog/backend/TroublogApplicationTests.java
Labels: 🚀 deploy

#19 [Fix] CD 과정 오류 수정
  .github/workflows/cd.yml
Labels: 🐛 fix

#33 [Feat] 유저 팔로우/팔로잉 API 개발
  src/main/java/troublog/backend/domain/auth/service/AuthService.java
  src/main/java/troublog/backend/domain/trouble/service/command/PostCommandService.java
  src/main/java/troublog/backend/domain/user/controller/UserController.java
  src/main/java/troublog/backend/domain/user/converter/FollowConverter.java
  src/main/java/troublog/backend/domain/user/converter/UserConverter.java
  src/main/java/troublog/backend/domain/user/dto/response/UserFollowsResDto.java
  src/main/java/troublog/backend/domain/user/entity/Follow.java
  src/main/java/troublog/backend/domain/user/entity/User.java
  src/main/java/troublog/backend/domain/user/repository/FollowRepository.java
  src/main/java/troublog/backend/domain/user/service/UserFacade.java
  src/main/java/troublog/backend/domain/user/service/command/FollowCommandService.java
  src/main/java/troublog/backend/domain/user/service/command/UserCommandService.java
  src/main/java/troublog/backend/domain/user/service/query/FollowQueryService.java
  src/main/java/troublog/backend/domain/user/service/query/UserQueryService.java
  src/main/java/troublog/backend/domain/user/validator/FollowValidator.java
  src/main/java/troublog/backend/global/common/error/ErrorCode.java
  src/main/java/troublog/backend/global/common/filter/JwtAuthenticationFilter.java
Labels: ✨ feat
