Repository IT-Cotato/11th-Troublog-BE, pull requests merged in 2025-08, with the labels that each got.

#35 [Feat] 사용자 정보 API 개발
  src/main/java/troublog/backend/domain/auth/controller/AuthController.java
  src/main/java/troublog/backend/domain/auth/service/AuthService.java
  src/main/java/troublog/backend/domain/user/controller/UserController.java
  src/main/java/troublog/backend/domain/user/converter/UserConverter.java
  src/main/java/troublog/backend/domain/user/dto/request/UserProfileUpdateReqDto.java
  src/main/java/troublog/backend/domain/user/dto/response/UserInfoResDto.java
  src/main/java/troublog/backend/domain/user/dto/response/UserProfileResDto.java
  src/main/java/troublog/backend/domain/user/entity/User.java
  src/main/java/troublog/backend/domain/user/service/UserFacade.java
  src/main/java/troublog/backend/domain/user/service/command/UserCommandService.java
  src/main/java/troublog/backend/domain/user/service/query/UserQueryService.java
  src/main/java/troublog/backend/domain/user/validator/UserValidator.java
  src/main/java/troublog/backend/global/common/error/ErrorCode.java
Labels: ✨ feat, ♻️ refactor

#52 [Feat] 트러블 슈팅 요약본 생성 및 조회 API 개발
  .gitignore
  build.gradle
  src/main/java/troublog/backend/domain/ai/common/service/AiTaskService.java
  src/main/java/troublog/backend/domain/ai/summary/converter/SummaryTaskConverter.java
  src/main/java/troublog/backend/domain/ai/summary/dto/common/ExtractedContentDto.java
  src/main/java/troublog/backend/domain/ai/summary/dto/response/SummarizedResDto.java
  src/main/java/troublog/backend/domain/ai/summary/dto/response/TaskStartResDto.java
  src/main/java/troublog/backend/domain/ai/summary/dto/response/TaskStatusResDto.java
  src/main/java/troublog/backend/domain/ai/summary/entity/SummaryTask.java
  src/main/java/troublog/backend/domain/ai/summary/enums/SummaryStatus.java
  src/main/java/troublog/backend/domain/ai/summary/repository/SummaryTaskRepository.java
  src/main/java/troublog/backend/domain/ai/summary/service/PostSummaryCompletionService.java
  src/main/java/troublog/backend/domain/ai/summary/service/PostSummaryService.java
  src/main/java/troublog/backend/domain/ai/summary/service/PostSummaryServiceImpl.java
  src/main/java/troublog/backend/domain/ai/summary/service/command/SummaryTaskCommandService.java
  src/main/java/troublog/backend/domain/ai/summary/service/facade/SummaryTaskFacade.java
  src/main/java/troublog/backend/domain/ai/summary/service/query/SummaryTaskQueryService.java
  src/main/java/troublog/backend/domain/ai/validator/TaskValidator.java
  src/main/java/troublog/backend/domain/trouble/controller/PostCommandController.java
  src/main/java/troublog/backend/domain/trouble/controller/PostQueryController.java
  src/main/java/troublog/backend/domain/trouble/converter/ContentConverter.java
  src/main/java/troublog/backend/domain/trouble/dto/request/SummaryTypeReqDto.java
  src/main/java/troublog/backend/domain/trouble/entity/Post.java
  src/main/java/troublog/backend/domain/trouble/repository/ContentRepository.java
  src/main/java/troublog/backend/domain/trouble/repository/PostRepository.java
  src/main/java/troublog/backend/domain/trouble/repository/PostTagRepository.java
  src/main/java/troublog/backend/domain/trouble/repository/TagRepository.java
  src/main/java/troublog/backend/domain/trouble/service/facade/PostCommandFacade.java
  src/main/java/troublog/backend/domain/trouble/service/facade/PostQueryFacade.java
  src/main/java/troublog/backend/domain/trouble/service/query/ContentQueryService.java
  src/main/java/troublog/backend/domain/trouble/service/query/PostQueryService.java
  src/main/java/troublog/backend/domain/trouble/service/query/PostTagQueryService.java
  src/main/java/troublog/backend/domain/trouble/service/query/TagQueryService.java
  src/main/java/troublog/backend/global/common/config/AiConfig.java
  src/main/java/troublog/backend/global/common/config/AsyncConfig.java
  src/main/java/troublog/backend/global/common/config/PromptProperties.java
  src/main/java/troublog/backend/global/common/config/RedisConfig.java
  src/main/java/troublog/backend/global/common/config/property/OpenAiProperties.java
  src/main/java/troublog/backend/global/common/error/ErrorCode.java
  src/main/java/troublog/backend/global/common/error/exception/AiTaskException.java
  src/main/java/troublog/backend/global/common/error/exception/handler/GlobalExceptionHandler.java
  src/main/java/troublog/backend/global/common/util/CustomLoggingAdvisor.java
  src/main/java/troublog/backend/global/common/util/IdGenerator.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/prompts/blog.st
  src/main/resources/prompts/interview.st
  src/main/resources/prompts/issue-management.st
  src/main/resources/prompts/resume.st
  src/main/resources/prompts/system.st
Labels: ✨ feat

#55 [Feat] 프로젝트 생성, 트러블슈팅 조회 API 개발
  src/main/java/troublog/backend/domain/project/controller/ProjectController.java
  src/main/java/troublog/backend/domain/project/converter/ProjectConverter.java
  src/main/java/troublog/backend/domain/project/dto/request/ProjectReqDto.java
  src/main/java/troublog/backend/domain/project/dto/response/ProjectDetailResDto.java
  src/main/java/troublog/backend/domain/project/dto/response/ProjectResDto.java
  src/main/java/troublog/backend/domain/project/entity/Project.java
  src/main/java/troublog/backend/domain/project/enums/ProjectPostStatus.java
  src/main/java/troublog/backend/domain/project/repository/ProjectRepository.java
  src/main/java/troublog/backend/domain/project/service/command/ProjectCommandService.java
  src/main/java/troublog/backend/domain/project/service/facade/ProjectCommandFacade.java
  src/main/java/troublog/backend/domain/project/service/facade/ProjectQueryFacade.java
  src/main/java/troublog/backend/domain/project/service/factory/ProjectFactory.java
  src/main/java/troublog/backend/domain/project/service/query/ProjectQueryService.java
  src/main/java/troublog/backend/domain/statistics/controller/StatisticsController.java
  src/main/java/troublog/backend/domain/trouble/controller/PostQueryController.java
  src/main/java/troublog/backend/domain/trouble/converter/ListConverter.java
  src/main/java/troublog/backend/domain/trouble/dto/response/TroubleListResDto.java
  src/main/java/troublog/backend/domain/trouble/enums/SortType.java
  src/main/java/troublog/backend/domain/trouble/enums/VisibilityType.java
  src/main/java/troublog/backend/domain/trouble/repository/PostRepository.java
  src/main/java/troublog/backend/domain/trouble/service/facade/PostQueryFacade.java
  src/main/java/troublog/backend/domain/trouble/service/query/PostQueryService.java
Labels: ✨ feat

#60 [Feat] 커뮤니티 게시글 조회, 검색 기능 구현
  src/main/java/troublog/backend/domain/ai/summary/service/PostSummaryCompletionService.java
  src/main/java/troublog/backend/domain/ai/summary/service/PostSummaryServiceImpl.java
  src/main/java/troublog/backend/domain/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/troublog/backend/domain/project/controller/ProjectController.java
  src/main/java/troublog/backend/domain/project/service/facade/ProjectQueryFacade.java
  src/main/java/troublog/backend/domain/trouble/controller/CommunityController.java
  src/main/java/troublog/backend/domain/trouble/controller/PostCommandController.java
  src/main/java/troublog/backend/domain/trouble/controller/PostQueryController.java
  src/main/java/troublog/backend/domain/trouble/controller/admin/PostAdminController.java
  src/main/java/troublog/backend/domain/trouble/converter/ListConverter.java
  src/main/java/troublog/backend/domain/trouble/converter/PostConverter.java
  src/main/java/troublog/backend/domain/trouble/dto/request/PostReqDto.java
  src/main/java/troublog/backend/domain/trouble/dto/response/CommunityListResDto.java
  src/main/java/troublog/backend/domain/trouble/dto/response/CommunityPostResDto.java
  src/main/java/troublog/backend/domain/trouble/dto/response/PostResDto.java
  src/main/java/troublog/backend/domain/trouble/entity/Post.java
  src/main/java/troublog/backend/domain/trouble/enums/ContentSummaryType.java
  src/main/java/troublog/backend/domain/trouble/enums/SortType.java
  src/main/java/troublog/backend/domain/trouble/repository/PostRepository.java
  src/main/java/troublog/backend/domain/trouble/service/facade/command/CommentCommandFacade.java
  src/main/java/troublog/backend/domain/trouble/service/facade/command/LikeCommandFacade.java
  src/main/java/troublog/backend/domain/trouble/service/facade/command/PostCommandFacade.java
  src/main/java/troublog/backend/domain/trouble/service/facade/query/CommentQueryFacade.java
  src/main/java/troublog/backend/domain/trouble/service/facade/query/PostQueryFacade.java
  src/main/java/troublog/backend/domain/trouble/service/facade/relation/CommentRelationFacade.java
  src/main/java/troublog/backend/domain/trouble/service/facade/relation/PostRelationFacade.java
  src/main/java/troublog/backend/domain/trouble/service/factory/PostFactory.java
  src/main/java/troublog/backend/domain/trouble/service/query/PostQueryService.java
  src/main/java/troublog/backend/domain/trouble/validator/PostValidator.java
  src/main/java/troublog/backend/domain/user/converter/UserConverter.java
  src/main/java/troublog/backend/domain/user/dto/response/PostCardUserInfoResDto.java
  src/main/java/troublog/backend/domain/user/entity/Follow.java
  src/main/java/troublog/backend/domain/user/repository/FollowRepository.java
  src/main/java/troublog/backend/domain/user/repository/UserRepository.java
  src/main/java/troublog/backend/domain/user/service/UserFacade.java
  src/main/java/troublog/backend/domain/user/service/query/FollowQueryService.java
  src/main/java/troublog/backend/domain/user/service/query/UserQueryService.java
  src/main/java/troublog/backend/global/common/config/RedisConfig.java
  src/main/java/troublog/backend/global/common/error/ErrorCode.java
  src/main/java/troublog/backend/global/common/util/JsonConverter.java
  src/main/resources/application.yml
Labels: ✨ feat

#68 [Feat] 사용자 ID 기반 트러블슈팅 목록 조회 및 검색 기능 추가
  src/main/java/troublog/backend/domain/trouble/controller/PostCommandController.java
  src/main/java/troublog/backend/domain/trouble/controller/PostQueryController.java
Labels: 🌐 api

#73 [Refactor] 커뮤니티 응답 수정, 최근 열람 조회 API 추가
  src/main/java/troublog/backend/domain/trouble/controller/CommunityController.java
  src/main/java/troublog/backend/domain/trouble/converter/CommentConverter.java
  src/main/java/troublog/backend/domain/trouble/dto/response/CommentResDto.java
  src/main/java/troublog/backend/domain/trouble/entity/Comment.java
  src/main/java/troublog/backend/domain/trouble/repository/PostRepository.java
  src/main/java/troublog/backend/domain/trouble/service/facade/command/RecentPostCommandFacade.java
  src/main/java/troublog/backend/domain/trouble/service/facade/query/PostQueryFacade.java
  src/main/java/troublog/backend/domain/trouble/service/query/PostQueryService.java
  src/main/java/troublog/backend/domain/trouble/service/query/RecentPostQueryService.java
Labels: ✨ feat, ♻️ refactor

#77 🔧 [Config] CORS 허용 도메인에 서버 도메인 추가
  src/main/java/troublog/backend/global/common/config/CorsConfig.java
Labels: 🔧 config

#92 [Fix] 커뮤니티 게시글 목록 좋아요 기준 정렬 기능 수정
  src/main/java/troublog/backend/domain/trouble/converter/PostConverter.java
  src/main/java/troublog/backend/domain/trouble/dto/request/PostReqDto.java
  src/main/java/troublog/backend/domain/trouble/dto/response/PostResDto.java
  src/main/java/troublog/backend/domain/trouble/entity/Post.java
  src/main/java/troublog/backend/domain/trouble/enums/TemplateType.java
  src/main/java/troublog/backend/domain/trouble/service/facade/query/PostQueryFacade.java
  src/main/java/troublog/backend/domain/trouble/service/facade/relation/PostRelationFacade.java
Labels: 🐛 fix, ♻️ refactor

#94 [Fix] Post 변경된 구조, QA 반영
  src/main/java/troublog/backend/domain/project/controller/ProjectController.java
  src/main/java/troublog/backend/domain/project/entity/Project.java
  src/main/java/troublog/backend/domain/project/service/command/ProjectCommandService.java
  src/main/java/troublog/backend/domain/project/service/facade/ProjectCommandFacade.java
  src/main/java/troublog/backend/domain/trouble/converter/ListConverter.java
  src/main/java/troublog/backend/domain/trouble/dto/response/TroubleListResDto.java
  src/main/java/troublog/backend/domain/trouble/repository/PostRepository.java
  src/main/java/troublog/backend/domain/trouble/repository/PostSummaryRepository.java
  src/main/java/troublog/backend/domain/trouble/service/query/PostQueryService.java
Labels: 🐛 fix, ♻️ refactor

#106 [Config] Security 설정 변경
  src/main/java/troublog/backend/domain/image/controller/ImageController.java
  src/main/java/troublog/backend/domain/image/service/facade/ImageFacade.java
  src/main/java/troublog/backend/domain/image/service/s3/S3Uploader.java
  src/main/java/troublog/backend/global/common/config/SecurityConfig.java
Labels: 🔧 config

#108 [Deploy] main branch 배포 진행
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: 🚀 deploy

#115 [Refacotr] 프로젝트 내 트러블슈팅 조회 API 상태 추가
  src/main/java/troublog/backend/domain/project/controller/ProjectController.java
  src/main/java/troublog/backend/domain/project/enums/ProjectPostStatus.java
  src/main/java/troublog/backend/domain/project/service/facade/ProjectQueryFacade.java
  src/main/java/troublog/backend/domain/trouble/repository/PostRepository.java
  src/main/java/troublog/backend/domain/trouble/service/query/PostQueryService.java
Labels: ♻️ refactor
